### ISSUE TITLE
500 / Interner Server-Fehler

### ISSUE THREAD

**Issue by hj-hefer** [solectrus/solectrus#3669]
### Beschreibung (auf Deutsch oder Englisch)

Bekomme Fehlermeldung: 500

Interner Server-Fehler
Sorry, da ist etwas schief gelaufen. Im Server-Protokoll finden sich weitere Details.

docker compose logs dashboard

Log ist angehangen.

Bis vor Update auf 0.18.0 ohne Probleme gelaufen.

mfg
Hefer

### Welche Version von SOLECTRUS verwendest du?

v0.18.0

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Synology Docker

### Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)

```text
/volume2/docker/solectrus_neu$ docker-compose logs dashboard
solectrus_neu-dashboard-1  | SOLECTRUS Photovoltaic Dashboard
solectrus_neu-dashboard-1  | Copyright (C) 2020-2024 Georg Ledermann
solectrus_neu-dashboard-1  | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
solectrus_neu-dashboard-1  | Version v0.18.0, built on 2024-11-10T11:26:08+01:00
solectrus_neu-dashboard-1  | Using ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-linux-musl]
solectrus_neu-dashboard-1  | Based on Alpine Linux 3.20.3
solectrus_neu-dashboard-1  |
solectrus_neu-dashboard-1  | ## Waiting for services...
solectrus_neu-dashboard-1  | redis (172.19.0.3:6379) open
solectrus_neu-dashboard-1  | Redis is up and running!
solectrus_neu-dashboard-1  | influxdb (172.19.0.4:8086) open
solectrus_neu-dashboard-1  | InfluxDB is up and running!
solectrus_neu-dashboard-1  | postgresql (172.19.0.2:5432) open
solectrus_neu-dashboard-1  | PostgreSQL is up and running!
solectrus_neu-dashboard-1  |
solectrus_neu-dashboard-1  | ## Preparing database...
solectrus_neu-dashboard-1  | Database is ready!
solectrus_neu-dashboard-1  |
solectrus_neu-dashboard-1  | ## Starting Rails application...
solectrus_neu-dashboard-1  | => Booting Puma
solectrus_neu-dashboard-1  | => Rails 7.2.2 application starting in production
solectrus_neu-dashboard-1  | => Run `bin/rails server --help` for more startup options
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.620162 #1]  INFO -- : Sensor initialization started
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621138 #1]  INFO -- :   - Sensor 'inverter_power' mapped to 'SENEC:inverter_power'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621184 #1]  INFO -- :   - Sensor 'inverter_power_forecast' mapped to 'forecast:watt'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621216 #1]  INFO -- :   - Sensor 'house_power' mapped to 'SENEC:house_power'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621249 #1]  INFO -- :   - Sensor 'heatpump_power' ignored
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621280 #1]  INFO -- :   - Sensor 'grid_import_power' mapped to 'SENEC:grid_power_plus'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621311 #1]  INFO -- :   - Sensor 'grid_export_power' mapped to 'SENEC:grid_power_minus'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621341 #1]  INFO -- :   - Sensor 'grid_export_limit' mapped to 'SENEC:power_ratio'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621373 #1]  INFO -- :   - Sensor 'battery_charging_power' mapped to 'SENEC:bat_power_plus'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621404 #1]  INFO -- :   - Sensor 'battery_discharging_power' mapped to 'SENEC:bat_power_minus'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621435 #1]  INFO -- :   - Sensor 'battery_soc' mapped to 'SENEC:bat_fuel_charge'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621465 #1]  INFO -- :   - Sensor 'car_battery_soc' ignored
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621497 #1]  INFO -- :   - Sensor 'wallbox_car_connected' ignored
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621528 #1]  INFO -- :   - Sensor 'wallbox_power' mapped to 'pv:wallbox_power'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621570 #1]  INFO -- :   - Sensor 'case_temp' mapped to 'SENEC:case_temp'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621601 #1]  INFO -- :   - Sensor 'system_status' mapped to 'SENEC:current_state'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621632 #1]  INFO -- :   - Sensor 'system_status_ok' mapped to 'SENEC:current_state_ok'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621663 #1]  INFO -- :   - Sensor 'house_power_grid' mapped to 'power_splitter:house_power_grid'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621697 #1]  INFO -- :   - Sensor 'wallbox_power_grid' mapped to 'power_splitter:wallbox_power_grid'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621729 #1]  INFO -- :   - Sensor 'heatpump_power_grid' mapped to 'power_splitter:heatpump_power_grid'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621762 #1]  INFO -- :   - Sensor 'house_power' excluded wallbox_power
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.621796 #1]  INFO -- : Sensor initialization completed
solectrus_neu-dashboard-1  | I, [2024-11-12T19:16:40.708505 #1]  INFO -- : Configuration checked, no changes detected, summaries are still valid.
solectrus_neu-dashboard-1  | Puma starting in single mode...
solectrus_neu-dashboard-1  | * Puma version: 6.4.3 (ruby 3.3.6-p108) ("The Eagle of Durango")
solectrus_neu-dashboard-1  | *  Min threads: 3
solectrus_neu-dashboard-1  | *  Max threads: 3
solectrus_neu-dashboard-1  | *  Environment: production
solectrus_neu-dashboard-1  | *          PID: 1
solectrus_neu-dashboard-1  | * Listening on http://0.0.0.0:3000
solectrus_neu-dashboard-1  | Use Ctrl-C to stop
solectrus_neu-dashboard-1  | I, [2024-11-12T19:17:09.459246 #1]  INFO -- : [172.19.0.1] method=GET path=/inverter_power/now format=html controller=HomeController action=index status=200 allocations=100679 duration=972.89 view=487.67 db=0.00
solectrus_neu-dashboard-1  | I, [2024-11-12T19:17:10.082527 #1]  INFO -- : [172.19.0.1] method=GET path=/charts/inverter_power/now format=html controller=ChartsController action=index status=200 allocations=44500 duration=303.34 view=302.19 db=0.00
solectrus_neu-dashboard-1  | I, [2024-11-12T19:17:10.216111 #1]  INFO -- : [172.19.0.1] method=GET path=/stats/inverter_power/now format=html controller=StatsController action=index status=500 allocations=54476 duration=459.79 view=0.00 db=0.00
solectrus_neu-dashboard-1  | E, [2024-11-12T19:17:10.226659 #1] ERROR -- : [172.19.0.1]
solectrus_neu-dashboard-1  | [172.19.0.1] ActionView::Template::Error (comparison of Float with nil failed):
solectrus_neu-dashboard-1  | [172.19.0.1]
solectrus_neu-dashboard-1  | Causes:
solectrus_neu-dashboard-1  | [172.19.0.1] ArgumentError (comparison of Float with nil failed)
solectrus_neu-dashboard-1  | [172.19.0.1]     10: turbo-stream action="morph" target="stats" children-only= true
solectrus_neu-dashboard-1  | [172.19.0.1]     11:   template
solectrus_neu-dashboard-1  | [172.19.0.1]     12:     - if timeframe.now?
solectrus_neu-dashboard-1  | [172.19.0.1]     13:       = render StatsNow::Component.new calculator:, sensor:
solectrus_neu-dashboard-1  | [172.19.0.1]     14:     - else
solectrus_neu-dashboard-1  | [172.19.0.1]     15:       = render StatsRange::Component.new calculator:, timeframe:, sensor:
solectrus_neu-dashboard-1  | [172.19.0.1]
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/stats_now/component.rb:16:in `max'
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/stats_now/component.rb:16:in `max_flow'
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/stats_now/component.html.slim:46:in `block (2 levels) in call'
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/stats_now/component.html.slim:89:in `block in call'
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/balance/component.html.slim:13:in `call'
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/stats_now/component.html.slim:1:in `call'
solectrus_neu-dashboard-1  | [172.19.0.1] app/views/stats/index.turbo_stream.slim:13
solectrus_neu-dashboard-1  | [172.19.0.1] app/controllers/stats_controller.rb:8:in `index'
solectrus_neu-dashboard-1  | [172.19.0.1] app/controllers/concerns/auto_locale.rb:14:in `switch_locale'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:17:10.262528 #1]  INFO -- : [172.19.0.1] method=GET path=/500 format=html controller=ErrorsController action=show status=500 allocations=7519 duration=29.27 view=26.22 db=0.00
solectrus_neu-dashboard-1  | I, [2024-11-12T19:17:10.759958 #1]  INFO -- : [172.19.0.1] method=GET path=/stats/inverter_power/now format=html controller=StatsController action=index status=500 allocations=9130 duration=244.22 view=0.00 db=0.00
solectrus_neu-dashboard-1  | E, [2024-11-12T19:17:10.768981 #1] ERROR -- : [172.19.0.1]
solectrus_neu-dashboard-1  | [172.19.0.1] ActionView::Template::Error (comparison of Float with nil failed):
solectrus_neu-dashboard-1  | [172.19.0.1]
solectrus_neu-dashboard-1  | Causes:
solectrus_neu-dashboard-1  | [172.19.0.1] ArgumentError (comparison of Float with nil failed)
solectrus_neu-dashboard-1  | [172.19.0.1]     10: turbo-stream action="morph" target="stats" children-only= true
solectrus_neu-dashboard-1  | [172.19.0.1]     11:   template
solectrus_neu-dashboard-1  | [172.19.0.1]     12:     - if timeframe.now?
solectrus_neu-dashboard-1  | [172.19.0.1]     13:       = render StatsNow::Component.new calculator:, sensor:
solectrus_neu-dashboard-1  | [172.19.0.1]     14:     - else
solectrus_neu-dashboard-1  | [172.19.0.1]     15:       = render StatsRange::Component.new calculator:, timeframe:, sensor:
solectrus_neu-dashboard-1  | [172.19.0.1]
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/stats_now/component.rb:16:in `max'
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/stats_now/component.rb:16:in `max_flow'
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/stats_now/component.html.slim:46:in `block (2 levels) in call'
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/stats_now/component.html.slim:89:in `block in call'
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/balance/component.html.slim:13:in `call'
solectrus_neu-dashboard-1  | [172.19.0.1] app/components/stats_now/component.html.slim:1:in `call'
solectrus_neu-dashboard-1  | [172.19.0.1] app/views/stats/index.turbo_stream.slim:13
solectrus_neu-dashboard-1  | [172.19.0.1] app/controllers/stats_controller.rb:8:in `index'
solectrus_neu-dashboard-1  | [172.19.0.1] app/controllers/concerns/auto_locale.rb:14:in `switch_locale'
solectrus_neu-dashboard-1  | I, [2024-11-12T19:17:10.936046 #1]  INFO -- : [172.19.0.1] method=GET path=/500 format=html controller=ErrorsController action=show status=500 allocations=9594 duration=164.24 view=160.56 db=0.00
```

### Dein vollständiges `.env`

```text
##################################################################
###                          Generic                           ###
##################################################################

TZ=Europe/Berlin

##################################################################
###                   Dashboard application                    ###
##################################################################

# Domain name or IP address of your host
APP_HOST=xxxx

# Date of commissioning of your photovoltaic system
INSTALLATION_DATE=2020-01-20

# Password to login as administrator, required to manage settings like historical prices
ADMIN_PASSWORD=xxxx

# Interval in seconds for polling the InfluxDB
INFLUX_POLL_INTERVAL=5

# SSL redirect: Use "true" if you want to auto-redirect to https, but ensure that you have a valid SSL certificate
# and a reverse proxy in front of the app!
# In all other cases, the option must be "false"!
FORCE_SSL=false

# Secret token to secure cookies, 128 chars long hexadecimal encoded string
SECRET_KEY_BASE=ae44350a0818503081eb24dc455292ca220fe3ffbefc55087e8e58d6151a6d54b7aeb69b03a531d88de297d819abf1427f41c77c35120e368ea0b0a79b0cc56b

# Start web server Puma in single mode (recommended to reduce memory usage)
WEB_CONCURRENCY=0

# Optional: Allow iframe embedding
# FRAME_ANCESTORS=https://my-other-home-automation-software.com

# Optional: Set factor to calculate CO2 emissions (default: 401 g/kWh)
# CO2_EMISSION_FACTOR=500

# Password for the PostgreSQL database, used by the app to communicate internally with the database
# Caution: Do not change this after the first run, otherwise the app will no longer be able to connect to the database!
POSTGRES_PASSWORD=my-secret-db-password

##################################################################
###                      Sensor mapping                        ###
##################################################################

# Where to find the data in the InfluxDB
# Each sensor must be mapped to a measurement and a field
# The format is: INFLUX_SENSOR_NAME=MEASUREMENT:FIELD
# Example: INFLUX_SENSOR_INVERTER_POWER=my_pv:inverter_power

INFLUX_SENSOR_INVERTER_POWER=SENEC:inverter_power
INFLUX_SENSOR_HOUSE_POWER=SENEC:house_power
INFLUX_SENSOR_GRID_IMPORT_POWER=SENEC:grid_power_plus
INFLUX_SENSOR_GRID_EXPORT_POWER=SENEC:grid_power_minus
INFLUX_SENSOR_BATTERY_CHARGING_POWER=SENEC:bat_power_plus
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=SENEC:bat_power_minus
INFLUX_SENSOR_BATTERY_SOC=SENEC:bat_fuel_charge
INFLUX_SENSOR_WALLBOX_POWER=pv:wallbox_power
INFLUX_SENSOR_CASE_TEMP=SENEC:case_temp
INFLUX_SENSOR_SYSTEM_STATUS=SENEC:current_state
INFLUX_SENSOR_SYSTEM_STATUS_OK=SENEC:current_state_ok
INFLUX_SENSOR_GRID_EXPORT_LIMIT=SENEC:power_ratio
INFLUX_SENSOR_INVERTER_POWER_FORECAST=forecast:watt
# INFLUX_SENSOR_HEATPUMP_POWER=

# Optional: Exclude sensors from house power calculation
# Default is HEATPUMP_POWER (if defined)
INFLUX_EXCLUDE_FROM_HOUSE_POWER=WALLBOX_POWER

##################################################################
###                      SENEC Collector                       ###
##################################################################

# The adapter to use
# Values: local, cloud
SENEC_ADAPTER=local

# The IP address or hostname of your SENEC device
# Available only when using the local adapter
SENEC_HOST=xxxx

# The schema protocol to use
# Available only when using the local adapter
# Values: http, https
SENEC_SCHEMA=https

# The language to use for status strings
# Available only when using the local adapter
# Values: de, en, it
SENEC_LANGUAGE=de

# The credentials for mein-senec.de
# Available only when using the cloud adapter
# SENEC_USERNAME=me@example.com
# SENEC_PASSWORD=my-senec-password

# The system ID of your SENEC device
# Available only when using the cloud adapter
# Can be empty if there is just one system
# SENEC_SYSTEM_ID=123456

# The interval in seconds for polling
# Minimum for local adapter is 5 seconds
# Minimum for cloud adapter is 30 seconds
SENEC_INTERVAL=5

# Measurement name for InfluxDB
SENEC_INFLUX_MEASUREMENT=SENEC

# Optional: Disable specific fields you do not want to send to InfluxDB.
# This can be useful if you are tracking them from another source.
# Comma separated list of fields, no whitespace. Example:
SENEC_IGNORE=wallbox_charge_power

##################################################################
###                       MQTT Collector                       ###
##################################################################

##### MQTT Broker credentials
#MQTT_HOST=192.168.11.107
#MQTT_PORT=1883
#MQTT_SSL=false
# MQTT_USERNAME=my-mqtt-username
# MQTT_PASSWORD=my-mqtt-password

##### Mappings

# Index of the mappings, starting with 0
# Example:
#
# MAPPING_0_TOPIC=example-device/0/ENERGY/INVERTER_POWER
# MAPPING_0_MEASUREMENT=EXAMPLE
# MAPPING_0_FIELD=inverter_power
# MAPPING_0_TYPE=integer # One of integer, float, string, boolean
#
# MAPPING_1_TOPIC=example-device/0/ENERGY/BAT_CHARGE_POWER
# MAPPING_1_MEASUREMENT=EXAMPLE
# MAPPING_1_FIELD=battery_charging_power
# MAPPING_1_TYPE=float
#
# ...
MAPPING_0_TOPIC=openWB/set/pv/2/get/power
MAPPING_0_MEASUREMENT=SENEC
MAPPING_0_FIELD=inverter_power
MAPPING_0_TYPE=integer
MAPPING_1_TOPIC=openWB/set/counter/0/get/imported
MAPPING_1_MEASUREMENT=SENEC
MAPPING_1_FIELD=house_power
MAPPING_1_TYPE=integer
MAPPING_2_TOPIC=openWB/set/counter/0/get/power
MAPPING_2_MEASUREMENT_POSITIVE=SENEC
MAPPING_2_MEASUREMENT_NEGATIVE=SENEC
MAPPING_2_FIELD_POSITIVE=grid_power_plus
MAPPING_2_FIELD_NEGATIVE=grid_power_minus
MAPPING_2_TYPE=integer
MAPPING_3_TOPIC=openWB/set/bat/1/get/power
MAPPING_3_MEASUREMENT_POSITIVE=SENEC
MAPPING_3_MEASUREMENT_NEGATIVE=SENEC
MAPPING_3_FIELD_POSITIVE=bat_power_plus
MAPPING_3_FIELD_NEGATIVE=bat_power_minus
MAPPING_3_TYPE=integer
MAPPING_4_TOPIC=openWB/set/bat/1/get/soc
MAPPING_4_MEASUREMENT=SENEC
MAPPING_4_FIELD=bat_fuel_charge
MAPPING_4_TYPE=float
MAPPING_5_TOPIC=mqtt/0/openWB/chargepoint/4/get/power
MAPPING_5_MEASUREMENT=pv
MAPPING_5_FIELD=wallbox_power
MAPPING_5_TYPE=integer
MAPPING_6_TOPIC=senec/0/TEMPMEASURE/CASE TEMP
MAPPING_6_MEASUREMENT=SENEC
MAPPING_6_FIELD=case_temp
MAPPING_6_TYPE=float

##################################################################
###                       Power Splitter                       ###
##################################################################

# Interval in seconds to run the calculation (default: 3600, min: 300)
# POWER_SPLITTER_INTERVAL=3600

##################################################################
###                     Forecast collector                     ###
##################################################################

FORECAST_PROVIDER=forecast.solar

# Number of planes (if you have more than one). Default is 1. Forecast.solar allows up to 4 planes, Solcast up to 2.
FORECAST_CONFIGURATIONS=2

# Update interval in seconds
FORECAST_INTERVAL=1800

# Measurement name for InfluxDB
FORECAST_INFLUX_MEASUREMENT=forecast

### Details for forecast.solar
# API docs: https://doc.forecast.solar/doku.php?id=api:estimate

# Latitude of the plant location
FORECAST_LATITUDE=xxx

# Longitude of the plant location
FORECAST_LONGITUDE=xxx

# Plane declination: 0 (horizontal) - 90 (vertical)
# FORECAST_DECLINATION=30

# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
# FORECAST_AZIMUTH=20

# Installed modules power in kilowatt peak (kWp)
# FORECAST_KWP=8.4

# Optional damping factors (http://doc.forecast.solar/damping)
# FORECAST_DAMPING_MORNING=0.5
# FORECAST_DAMPING_EVENING=0
#
# Optional configuration for multiple planes
#
# Starting from 0, add params different from the values defined above
FORECAST_0_DECLINATION=23
# FORECAST_0_AZIMUTH=-180
FORECAST_0_KWP=2.66
#
FORECAST_1_DECLINATION=23
FORECAST_1_AZIMUTH=90
FORECAST_1_KWP=3.04
#
# FORECAST_2_DECLINATION=50
# FORECAST_2_AZIMUTH=0
# FORECAST_2_KWP=7.84
#
# FORECAST_3_DECLINATION=50
# FORECAST_3_AZIMUTH=90
# FORECAST_3_KWP=2.58
#
# Available params are:
# - FORECAST_x_LATITUDE
# - FORECAST_x_LONGITUDE
# - FORECAST_x_DECLINATION
# - FORECAST_x_AZIMUTH
# - FORECAST_x_KWP
# - FORECAST_x_DAMPING_MORNING
# - FORECAST_x_DAMPING_EVENING

# Optional API key for registered users of forecast.solar (https://doc.forecast.solar/account_models)
# FORECAST_SOLAR_APIKEY=abc123

### Details for solcast.com

# SOLCAST_APIKEY=secret-solcast-api-key
SOLCAST_SITE=1111-2222-3333-4444

# SOLCAST_0_SITE=1111-2222-3333-4444
# SOLCAST_1_SITE=5555-6666-7777-8888

##################################################################
###                 InfluxDB time series database              ###
##################################################################

# InfluxDB host
INFLUX_HOST=influxdb

# InfluxDB schema (http or https)
INFLUX_SCHEMA=http

# InfluxDB port
INFLUX_PORT=8086

# Credentials for the InfluxDB, don't change after the first run!
INFLUX_ORG=solectrus
INFLUX_USERNAME=Joerg
INFLUX_PASSWORD=PBab8662
INFLUX_ADMIN_TOKEN=PBab8662

# Set these names before first run, they can't be changed later!
INFLUX_BUCKET=solectrus

# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, you can use two separate tokens, created via the InfluxDB frontend.
INFLUX_TOKEN_WRITE=PBab8662
INFLUX_TOKEN_READ=PBab8662

# Volume path for storing the InfluxDB data
INFLUX_VOLUME_PATH=/volume2/docker/solectrus_neu/influxdb

##################################################################
###                    PostgreSQL database                     ###
##################################################################

# Volume path for storing the PostgreSQL data
DB_VOLUME_PATH=/volume2/docker/solectrus_neu/postgresql

##################################################################
###                 Redis in-memory database                   ###
##################################################################

# Volume path for storing the database snapshot
REDIS_VOLUME_PATH=/volume2/docker/solectrus_neu/redis

# URL of the Redis database
REDIS_URL=redis://redis:6379/1
```

**Comment by hj-hefer** [comment]
Tagesdaten lassen sich über xxx/inverter_power/2024-09-10 aufrufen. auch die Wochen/Monats usw. daten. Nur aktuell kommt die Fehlermeldung. 
Tageszusammenfassung? Wo finde ich die? Oben bei den Reitern mit Einzelwerte usw.?

**Comment by ledermann** [comment]
Ok, das ist schon mal gut. Ist dann vermutlich keine große Sache.

Bezüglich Tageszusammenfassungen hier ein paar Links:
- https://solectrus.de/blog/2024-11-10-version-0-18/
- https://github.com/solectrus/solectrus/releases/tag/v0.18.0
- https://github.com/solectrus/solectrus/pull/3533

Anders gefragt: Hast du irgendwo den neuen Fortschrittsbalken gesehen? Der erscheint, wenn man nach dem Update auf 0.18 irgendeine Zeitraum (z.B. Monat, Jahr, GESAMT usw) aufruft.

Könntest du bitte noch folgendes versuchen (Redis-Cache löschen):

```
docker compose exec redis redis-cli FLUSHALL
```

Antwort wird ein "OK" sein. Tritt das Problem dann immer noch auf?

**Comment by hj-hefer** [comment]
Fortschrittbalken habe ich gesehen und unter Einstellungen steht Tageszusammenfassung-Es sind 100% der benötigten Zusammenfassungen vorhanden.

Der Befehl des Cache löschen brachte das ok aber leider keinen erfolg.

**Comment by bergfex** [comment]
Bei mir war der gleiche Fehler. Mit der Entwicklerversion scheint wieder alles normal zu laufen. Danke für die schnelle Hilfe

**Comment by ledermann** [comment]
@bergfex Danke für die Bestätigung. Ich habe die Fehlerkorrektur jetzt als `v0.18.1` bereitgestellt. Es kann also wieder zurück auf `latest` gewechselt werden.

Danke für das allseitige Feedback 👍

**Comment by hj-hefer** [comment]
Vielen Dank, bin erst heute früh dazu gekommen es zu testen und es funktioniert
