### ISSUE TITLE
wieder Fehler 500 bei Custom Verbraucher Tag, Woche etc. - aktuell funktioniert 

### ISSUE THREAD

**Issue by Zeppelin-PV** [solectrus/solectrus#3757]
### Beschreibung (auf Deutsch oder Englisch)

![grafik](https://github.com/user-attachments/assets/813548ce-7aa5-42d4-afe5-d10fa47519f9)

### Welche Version von SOLECTRUS verwendest du?

pr-3747

### Auf welchem Gerät läuft bei dir SOLECTRUS?

PI4

### Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)

```text
root@raspberrypi:/home/pi/solectrus#  docker compose logs dashboard
dashboard-1  | SOLECTRUS Photovoltaic Dashboard
dashboard-1  | Copyright (C) 2020-2024 Georg Ledermann
dashboard-1  | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
dashboard-1  | Version v0.18.2-76-g0418ef05 (custom-consumers), built on 2024-12-07T14:18:52+01:00
dashboard-1  | Using ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [aarch64-linux-musl]
dashboard-1  | Based on Alpine Linux 3.21.0
dashboard-1  | 
dashboard-1  | ## Waiting for services...
dashboard-1  | redis (172.18.0.4:6379) open
dashboard-1  | Redis is up and running!
dashboard-1  | influxdb (172.18.0.3:8086) open
dashboard-1  | InfluxDB is up and running!
dashboard-1  | postgresql (172.18.0.5:5432) open
dashboard-1  | PostgreSQL is up and running!
dashboard-1  | 
dashboard-1  | ## Preparing database...
dashboard-1  | Database is ready!
dashboard-1  | 
dashboard-1  | ## Starting Rails application...
dashboard-1  | => Booting Puma
dashboard-1  | => Rails 7.2.2 application starting in production 
dashboard-1  | => Run `bin/rails server --help` for more startup options
dashboard-1  | I, [2024-12-07T19:44:48.897102 #1]  INFO -- : Sensor initialization started
dashboard-1  | I, [2024-12-07T19:44:48.898431 #1]  INFO -- :   - Sensor 'inverter_power' mapped to 'SENEC:inverter_power'
dashboard-1  | I, [2024-12-07T19:44:48.898495 #1]  INFO -- :   - Sensor 'inverter_power_forecast' mapped to 'Forecast:watt'
dashboard-1  | I, [2024-12-07T19:44:48.898532 #1]  INFO -- :   - Sensor 'house_power' mapped to 'SENEC:house_power'
dashboard-1  | I, [2024-12-07T19:44:48.898567 #1]  INFO -- :   - Sensor 'heatpump_power' ignored
dashboard-1  | I, [2024-12-07T19:44:48.898601 #1]  INFO -- :   - Sensor 'grid_import_power' mapped to 'SENEC:grid_power_plus'
dashboard-1  | I, [2024-12-07T19:44:48.898635 #1]  INFO -- :   - Sensor 'grid_export_power' mapped to 'SENEC:grid_power_minus'
dashboard-1  | I, [2024-12-07T19:44:48.898668 #1]  INFO -- :   - Sensor 'grid_export_limit' mapped to 'SENEC:power_ratio'
dashboard-1  | I, [2024-12-07T19:44:48.898700 #1]  INFO -- :   - Sensor 'battery_charging_power' mapped to 'SENEC:bat_power_plus'
dashboard-1  | I, [2024-12-07T19:44:48.898734 #1]  INFO -- :   - Sensor 'battery_discharging_power' mapped to 'SENEC:bat_power_minus'
dashboard-1  | I, [2024-12-07T19:44:48.898767 #1]  INFO -- :   - Sensor 'battery_soc' mapped to 'SENEC:bat_fuel_charge'
dashboard-1  | I, [2024-12-07T19:44:48.898799 #1]  INFO -- :   - Sensor 'car_battery_soc' ignored
dashboard-1  | I, [2024-12-07T19:44:48.898832 #1]  INFO -- :   - Sensor 'wallbox_car_connected' ignored
dashboard-1  | I, [2024-12-07T19:44:48.898864 #1]  INFO -- :   - Sensor 'wallbox_power' ignored
dashboard-1  | I, [2024-12-07T19:44:48.898896 #1]  INFO -- :   - Sensor 'case_temp' mapped to 'SENEC:case_temp'
dashboard-1  | I, [2024-12-07T19:44:48.898929 #1]  INFO -- :   - Sensor 'system_status' mapped to 'SENEC:current_state'
dashboard-1  | I, [2024-12-07T19:44:48.898961 #1]  INFO -- :   - Sensor 'system_status_ok' mapped to 'SENEC:current_state_ok'
dashboard-1  | I, [2024-12-07T19:44:48.898993 #1]  INFO -- :   - Sensor 'house_power_grid' mapped to 'power_splitter:house_power_grid'
dashboard-1  | I, [2024-12-07T19:44:48.899027 #1]  INFO -- :   - Sensor 'wallbox_power_grid' mapped to 'power_splitter:wallbox_power_grid'
dashboard-1  | I, [2024-12-07T19:44:48.899060 #1]  INFO -- :   - Sensor 'heatpump_power_grid' mapped to 'power_splitter:heatpump_power_grid'
dashboard-1  | I, [2024-12-07T19:44:48.899093 #1]  INFO -- :   - Sensor 'custom_power_01' mapped to 'AUFZUG:power'
dashboard-1  | I, [2024-12-07T19:44:48.899126 #1]  INFO -- :   - Sensor 'custom_power_02' mapped to 'THERME:power'
dashboard-1  | I, [2024-12-07T19:44:48.899158 #1]  INFO -- :   - Sensor 'custom_power_03' ignored
dashboard-1  | I, [2024-12-07T19:44:48.899189 #1]  INFO -- :   - Sensor 'custom_power_04' ignored
dashboard-1  | I, [2024-12-07T19:44:48.899222 #1]  INFO -- :   - Sensor 'custom_power_05' ignored
dashboard-1  | I, [2024-12-07T19:44:48.899253 #1]  INFO -- :   - Sensor 'custom_power_06' ignored
dashboard-1  | I, [2024-12-07T19:44:48.899285 #1]  INFO -- :   - Sensor 'custom_power_07' ignored
dashboard-1  | I, [2024-12-07T19:44:48.899317 #1]  INFO -- :   - Sensor 'custom_power_08' ignored
dashboard-1  | I, [2024-12-07T19:44:48.899349 #1]  INFO -- :   - Sensor 'custom_power_09' ignored
dashboard-1  | I, [2024-12-07T19:44:48.899381 #1]  INFO -- :   - Sensor 'custom_power_10' mapped to 'TERRASSE:power_a'
dashboard-1  | I, [2024-12-07T19:44:48.899414 #1]  INFO -- :   - Sensor 'house_power' remains unchanged
dashboard-1  | I, [2024-12-07T19:44:48.899449 #1]  INFO -- : Sensor initialization completed
dashboard-1  | I, [2024-12-07T19:44:49.002963 #1]  INFO -- : Configuration checked, no changes detected, summaries are still valid.
dashboard-1  | Puma starting in single mode...
dashboard-1  | * Puma version: 6.5.0 ("Sky's Version")
dashboard-1  | * Ruby version: ruby 3.3.6 (2024-11-05 revision 75015d4c1f) +YJIT [aarch64-linux-musl]
dashboard-1  | *  Min threads: 3
dashboard-1  | *  Max threads: 3
dashboard-1  | *  Environment: production
dashboard-1  | *          PID: 1
dashboard-1  | * Listening on http://0.0.0.0:3000
dashboard-1  | Use Ctrl-C to stop
dashboard-1  | I, [2024-12-07T19:45:12.411806 #1]  INFO -- : [192.168.1.110] [ActiveJob] [SummarizerJob] [55aeb689-7e57-4665-92a2-410cc55d56aa] Performing SummarizerJob (Job ID: 55aeb689-7e57-4665-92a2-410cc55d56aa) from Async(default) with arguments: Sat, 07 Dec 2024
dashboard-1  | I, [2024-12-07T19:45:12.741155 #1]  INFO -- : [192.168.1.110] [ActiveJob] [SummarizerJob] [55aeb689-7e57-4665-92a2-410cc55d56aa] Performed SummarizerJob (Job ID: 55aeb689-7e57-4665-92a2-410cc55d56aa) from Async(default) in 334.14ms
dashboard-1  | I, [2024-12-07T19:45:13.328950 #1]  INFO -- : [192.168.1.110] method=GET path=/house/stats/custom_power_02/2024-12-07 format=html controller=House::StatsController action=index status=500 allocations=60845 duration=1323.97 view=0.00 db=115.36
dashboard-1  | E, [2024-12-07T19:45:13.339905 #1] ERROR -- : [192.168.1.110]   
dashboard-1  | [192.168.1.110] ActionView::Template::Error (nil can't be coerced into Float):
dashboard-1  | [192.168.1.110] 
dashboard-1  | Causes:
dashboard-1  | [192.168.1.110] TypeError (nil can't be coerced into Float)
dashboard-1  | [192.168.1.110]     53: 
dashboard-1  | [192.168.1.110]     54:           // Inner content
dashboard-1  | [192.168.1.110]     55:           .flex-1.flex
dashboard-1  | [192.168.1.110]     56:             = render SegmentContainer::Component.new tippy_placement: 'right',
dashboard-1  | [192.168.1.110]     57:                                                      calculator:,
dashboard-1  | [192.168.1.110]     58:                                                      timeframe: do |balance|
dashboard-1  | [192.168.1.110]     59:               ruby:
dashboard-1  | [192.168.1.110]   
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `*'
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `house_without_custom_costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `public_send'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:65:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:30:in `link_to_or_div'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:15:in `call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:5:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `each'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `call'
dashboard-1  | [192.168.1.110] app/views/house/stats/index.turbo_stream.slim:56
dashboard-1  | [192.168.1.110] app/controllers/house/stats_controller.rb:8:in `index'
dashboard-1  | [192.168.1.110] app/controllers/concerns/auto_locale.rb:14:in `switch_locale'
dashboard-1  | I, [2024-12-07T19:45:13.677037 #1]  INFO -- : [192.168.1.110] method=GET path=/500 format=html controller=ErrorsController action=show status=500 allocations=90832 duration=331.71 view=327.08 db=0.00
dashboard-1  | I, [2024-12-07T19:45:16.565312 #1]  INFO -- : [192.168.1.110] method=GET path=/house/stats/custom_power_02/2024-12-07 format=html controller=House::StatsController action=index status=500 allocations=7108 duration=229.32 view=0.00 db=9.42
dashboard-1  | E, [2024-12-07T19:45:16.602504 #1] ERROR -- : [192.168.1.110]   
dashboard-1  | [192.168.1.110] ActionView::Template::Error (nil can't be coerced into Float):
dashboard-1  | [192.168.1.110] 
dashboard-1  | Causes:
dashboard-1  | [192.168.1.110] TypeError (nil can't be coerced into Float)
dashboard-1  | [192.168.1.110]     53: 
dashboard-1  | [192.168.1.110]     54:           // Inner content
dashboard-1  | [192.168.1.110]     55:           .flex-1.flex
dashboard-1  | [192.168.1.110]     56:             = render SegmentContainer::Component.new tippy_placement: 'right',
dashboard-1  | [192.168.1.110]     57:                                                      calculator:,
dashboard-1  | [192.168.1.110]     58:                                                      timeframe: do |balance|
dashboard-1  | [192.168.1.110]     59:               ruby:
dashboard-1  | [192.168.1.110]   
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `*'
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `house_without_custom_costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `public_send'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:65:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:30:in `link_to_or_div'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:15:in `call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:5:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `each'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `call'
dashboard-1  | [192.168.1.110] app/views/house/stats/index.turbo_stream.slim:56
dashboard-1  | [192.168.1.110] app/controllers/house/stats_controller.rb:8:in `index'
dashboard-1  | [192.168.1.110] app/controllers/concerns/auto_locale.rb:14:in `switch_locale'
dashboard-1  | I, [2024-12-07T19:45:16.708725 #1]  INFO -- : [192.168.1.110] method=GET path=/500 format=html controller=ErrorsController action=show status=500 allocations=10313 duration=96.87 view=91.92 db=0.00
dashboard-1  | I, [2024-12-07T19:45:20.828852 #1]  INFO -- : [192.168.1.110] method=GET path=/ format=html controller=Balance::HomeController action=index status=302 allocations=684 duration=37.11 view=0.00 db=0.00 location=http://192.168.1.232:3000/house_power/now
dashboard-1  | I, [2024-12-07T19:45:21.163245 #1]  INFO -- : [192.168.1.110] method=GET path=/house_power/now format=html controller=Balance::HomeController action=index status=200 allocations=26191 duration=294.88 view=288.92 db=0.00
dashboard-1  | I, [2024-12-07T19:45:21.788860 #1]  INFO -- : [192.168.1.110] method=GET path=/stats/house_power/now format=html controller=Balance::StatsController action=index status=200 allocations=34704 duration=556.98 view=543.65 db=0.00
dashboard-1  | I, [2024-12-07T19:45:21.860506 #1]  INFO -- : [192.168.1.110] method=GET path=/charts/house_power/now format=html controller=Balance::ChartsController action=index status=200 allocations=56450 duration=584.98 view=575.95 db=0.00
dashboard-1  | I, [2024-12-07T19:45:23.090166 #1]  INFO -- : [192.168.1.110] method=GET path=/house_power/2024-12-07 format=html controller=Balance::HomeController action=index status=200 allocations=19934 duration=257.69 view=170.30 db=3.55
dashboard-1  | I, [2024-12-07T19:45:23.485304 #1]  INFO -- : [192.168.1.110] method=GET path=/stats/house_power/2024-12-07 format=html controller=Balance::StatsController action=index status=200 allocations=29641 duration=325.67 view=191.88 db=116.59
dashboard-1  | I, [2024-12-07T19:45:23.576174 #1]  INFO -- : [192.168.1.110] method=GET path=/charts/house_power/2024-12-07 format=html controller=Balance::ChartsController action=index status=200 allocations=56992 duration=330.36 view=327.66 db=0.00
dashboard-1  | I, [2024-12-07T19:45:24.506776 #1]  INFO -- : [192.168.1.110] method=GET path=/house/house_power/2024-12-07 format=html controller=House::HomeController action=index status=200 allocations=28229 duration=149.17 view=133.76 db=3.45
dashboard-1  | I, [2024-12-07T19:45:25.140011 #1]  INFO -- : [192.168.1.110] method=GET path=/house/charts/house_power/2024-12-07 format=html controller=House::ChartsController action=index status=200 allocations=31621 duration=168.72 view=166.25 db=0.00
dashboard-1  | I, [2024-12-07T19:45:25.171012 #1]  INFO -- : [192.168.1.110] method=GET path=/house/stats/house_power/2024-12-07 format=html controller=House::StatsController action=index status=500 allocations=36611 duration=208.54 view=0.00 db=92.51
dashboard-1  | E, [2024-12-07T19:45:25.179312 #1] ERROR -- : [192.168.1.110]   
dashboard-1  | [192.168.1.110] ActionView::Template::Error (nil can't be coerced into Float):
dashboard-1  | [192.168.1.110] 
dashboard-1  | Causes:
dashboard-1  | [192.168.1.110] TypeError (nil can't be coerced into Float)
dashboard-1  | [192.168.1.110]     53: 
dashboard-1  | [192.168.1.110]     54:           // Inner content
dashboard-1  | [192.168.1.110]     55:           .flex-1.flex
dashboard-1  | [192.168.1.110]     56:             = render SegmentContainer::Component.new tippy_placement: 'right',
dashboard-1  | [192.168.1.110]     57:                                                      calculator:,
dashboard-1  | [192.168.1.110]     58:                                                      timeframe: do |balance|
dashboard-1  | [192.168.1.110]     59:               ruby:
dashboard-1  | [192.168.1.110]   
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `*'
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `house_without_custom_costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `public_send'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:65:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:30:in `link_to_or_div'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:15:in `call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:5:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `each'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `call'
dashboard-1  | [192.168.1.110] app/views/house/stats/index.turbo_stream.slim:56
dashboard-1  | [192.168.1.110] app/controllers/house/stats_controller.rb:8:in `index'
dashboard-1  | [192.168.1.110] app/controllers/concerns/auto_locale.rb:14:in `switch_locale'
dashboard-1  | I, [2024-12-07T19:45:25.206989 #1]  INFO -- : [192.168.1.110] method=GET path=/500 format=html controller=ErrorsController action=show status=500 allocations=662 duration=23.90 view=11.66 db=0.00
dashboard-1  | I, [2024-12-07T19:45:25.310697 #1]  INFO -- : [192.168.1.110] method=GET path=/house/stats/house_power/2024-12-07 format=html controller=House::StatsController action=index status=500 allocations=7105 duration=68.08 view=0.00 db=6.93
dashboard-1  | E, [2024-12-07T19:45:25.316716 #1] ERROR -- : [192.168.1.110]   
dashboard-1  | [192.168.1.110] ActionView::Template::Error (nil can't be coerced into Float):
dashboard-1  | [192.168.1.110] 
dashboard-1  | Causes:
dashboard-1  | [192.168.1.110] TypeError (nil can't be coerced into Float)
dashboard-1  | [192.168.1.110]     53: 
dashboard-1  | [192.168.1.110]     54:           // Inner content
dashboard-1  | [192.168.1.110]     55:           .flex-1.flex
dashboard-1  | [192.168.1.110]     56:             = render SegmentContainer::Component.new tippy_placement: 'right',
dashboard-1  | [192.168.1.110]     57:                                                      calculator:,
dashboard-1  | [192.168.1.110]     58:                                                      timeframe: do |balance|
dashboard-1  | [192.168.1.110]     59:               ruby:
dashboard-1  | [192.168.1.110]   
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `*'
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `house_without_custom_costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `public_send'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:65:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:30:in `link_to_or_div'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:15:in `call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:5:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `each'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `call'
dashboard-1  | [192.168.1.110] app/views/house/stats/index.turbo_stream.slim:56
dashboard-1  | [192.168.1.110] app/controllers/house/stats_controller.rb:8:in `index'
dashboard-1  | [192.168.1.110] app/controllers/concerns/auto_locale.rb:14:in `switch_locale'
dashboard-1  | I, [2024-12-07T19:45:25.421616 #1]  INFO -- : [192.168.1.110] method=GET path=/500 format=html controller=ErrorsController action=show status=500 allocations=10352 duration=102.29 view=101.05 db=0.00
dashboard-1  | I, [2024-12-07T19:45:25.658595 #1]  INFO -- : [192.168.1.110] method=GET path=/house/house_power format=html controller=House::HomeController action=index status=302 allocations=318 duration=4.57 view=0.00 db=0.00 location=http://192.168.1.232:3000/house/house_power/now
dashboard-1  | I, [2024-12-07T19:45:25.831927 #1]  INFO -- : [192.168.1.110] method=GET path=/house/house_power/now format=html controller=House::HomeController action=index status=200 allocations=18988 duration=120.45 view=115.61 db=0.00
dashboard-1  | I, [2024-12-07T19:45:44.984138 #1]  INFO -- : [192.168.1.110] method=GET path=/ format=html controller=Balance::HomeController action=index status=302 allocations=547 duration=57.07 view=0.00 db=0.00 location=http://192.168.1.232:3000/house_power/now
dashboard-1  | I, [2024-12-07T19:45:45.234654 #1]  INFO -- : [192.168.1.110] method=GET path=/house_power/now format=html controller=Balance::HomeController action=index status=200 allocations=18944 duration=212.14 view=201.75 db=0.00
dashboard-1  | I, [2024-12-07T19:46:11.238919 #1]  INFO -- : [192.168.1.110] method=GET path=/inverter_power/now format=html controller=Balance::HomeController action=index status=200 allocations=18951 duration=124.68 view=112.03 db=0.00
dashboard-1  | I, [2024-12-07T19:46:11.559323 #1]  INFO -- : [192.168.1.110] method=GET path=/stats/inverter_power/now format=html controller=Balance::StatsController action=index status=200 allocations=22641 duration=219.92 view=216.99 db=0.00
dashboard-1  | I, [2024-12-07T19:46:11.625449 #1]  INFO -- : [192.168.1.110] method=GET path=/charts/inverter_power/now format=html controller=Balance::ChartsController action=index status=200 allocations=44423 duration=242.11 view=239.11 db=0.00
dashboard-1  | I, [2024-12-07T19:46:12.683038 #1]  INFO -- : [192.168.1.110] method=GET path=/charts/inverter_power/now format=html controller=Balance::ChartsController action=index status=200 allocations=33696 duration=136.40 view=135.02 db=0.00
dashboard-1  | I, [2024-12-07T19:46:12.729241 #1]  INFO -- : [192.168.1.110] method=GET path=/stats/inverter_power/now format=html controller=Balance::StatsController action=index status=200 allocations=45895 duration=193.98 view=193.06 db=0.00
dashboard-1  | I, [2024-12-07T19:46:14.436730 #1]  INFO -- : [192.168.1.110] method=GET path=/house/house_power/now format=html controller=House::HomeController action=index status=200 allocations=18991 duration=98.41 view=94.25 db=0.00
dashboard-1  | I, [2024-12-07T19:46:14.834659 #1]  INFO -- : [192.168.1.110] method=GET path=/house/charts/house_power/now format=html controller=House::ChartsController action=index status=200 allocations=31980 duration=138.46 view=133.47 db=0.00
dashboard-1  | I, [2024-12-07T19:46:14.874596 #1]  INFO -- : [192.168.1.110] method=GET path=/house/stats/house_power/now format=html controller=House::StatsController action=index status=200 allocations=39405 duration=198.76 view=195.87 db=0.00
dashboard-1  | I, [2024-12-07T19:46:15.487383 #1]  INFO -- : [192.168.1.110] method=GET path=/house/house_power/2024-12-07 format=html controller=House::HomeController action=index status=200 allocations=19953 duration=111.65 view=80.02 db=3.48
dashboard-1  | I, [2024-12-07T19:46:16.353228 #1]  INFO -- : [192.168.1.110] method=GET path=/house/charts/house_power/2024-12-07 format=html controller=House::ChartsController action=index status=200 allocations=25610 duration=180.74 view=176.94 db=0.00
dashboard-1  | I, [2024-12-07T19:46:16.389930 #1]  INFO -- : [192.168.1.110] method=GET path=/house/stats/house_power/2024-12-07 format=html controller=House::StatsController action=index status=500 allocations=31402 duration=228.28 view=0.00 db=137.72
dashboard-1  | E, [2024-12-07T19:46:16.396100 #1] ERROR -- : [192.168.1.110]   
dashboard-1  | [192.168.1.110] ActionView::Template::Error (nil can't be coerced into Float):
dashboard-1  | [192.168.1.110] 
dashboard-1  | Causes:
dashboard-1  | [192.168.1.110] TypeError (nil can't be coerced into Float)
dashboard-1  | [192.168.1.110]     53: 
dashboard-1  | [192.168.1.110]     54:           // Inner content
dashboard-1  | [192.168.1.110]     55:           .flex-1.flex
dashboard-1  | [192.168.1.110]     56:             = render SegmentContainer::Component.new tippy_placement: 'right',
dashboard-1  | [192.168.1.110]     57:                                                      calculator:,
dashboard-1  | [192.168.1.110]     58:                                                      timeframe: do |balance|
dashboard-1  | [192.168.1.110]     59:               ruby:
dashboard-1  | [192.168.1.110]   
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `*'
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `house_without_custom_costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `public_send'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:65:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:30:in `link_to_or_div'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:15:in `call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:5:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `each'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `call'
dashboard-1  | [192.168.1.110] app/views/house/stats/index.turbo_stream.slim:56
dashboard-1  | [192.168.1.110] app/controllers/house/stats_controller.rb:8:in `index'
dashboard-1  | [192.168.1.110] app/controllers/concerns/auto_locale.rb:14:in `switch_locale'
dashboard-1  | I, [2024-12-07T19:46:16.535951 #1]  INFO -- : [192.168.1.110] method=GET path=/500 format=html controller=ErrorsController action=show status=500 allocations=493 duration=126.73 view=99.43 db=0.00
dashboard-1  | I, [2024-12-07T19:46:16.691599 #1]  INFO -- : [192.168.1.110] method=GET path=/house/stats/house_power/2024-12-07 format=html controller=House::StatsController action=index status=500 allocations=7109 duration=69.74 view=0.00 db=7.94
dashboard-1  | E, [2024-12-07T19:46:16.694901 #1] ERROR -- : [192.168.1.110]   
dashboard-1  | [192.168.1.110] ActionView::Template::Error (nil can't be coerced into Float):
dashboard-1  | [192.168.1.110] 
dashboard-1  | Causes:
dashboard-1  | [192.168.1.110] TypeError (nil can't be coerced into Float)
dashboard-1  | [192.168.1.110]     53: 
dashboard-1  | [192.168.1.110]     54:           // Inner content
dashboard-1  | [192.168.1.110]     55:           .flex-1.flex
dashboard-1  | [192.168.1.110]     56:             = render SegmentContainer::Component.new tippy_placement: 'right',
dashboard-1  | [192.168.1.110]     57:                                                      calculator:,
dashboard-1  | [192.168.1.110]     58:                                                      timeframe: do |balance|
dashboard-1  | [192.168.1.110]     59:               ruby:
dashboard-1  | [192.168.1.110]   
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `*'
dashboard-1  | [192.168.1.110] app/services/calculator/range.rb:323:in `house_without_custom_costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `public_send'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:69:in `costs'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:65:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment/component.rb:30:in `link_to_or_div'
dashboard-1  | [192.168.1.110] app/components/segment/component.html.slim:15:in `call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:5:in `block in call'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `each'
dashboard-1  | [192.168.1.110] app/components/segment_container/component.html.slim:4:in `call'
dashboard-1  | [192.168.1.110] app/views/house/stats/index.turbo_stream.slim:56
dashboard-1  | [192.168.1.110] app/controllers/house/stats_controller.rb:8:in `index'
dashboard-1  | [192.168.1.110] app/controllers/concerns/auto_locale.rb:14:in `switch_locale'
dashboard-1  | I, [2024-12-07T19:46:16.755975 #1]  INFO -- : [192.168.1.110] method=GET path=/500 format=html controller=ErrorsController action=show status=500 allocations=10359 duration=59.76 view=49.61 db=0.00
dashboard-1  | I, [2024-12-07T19:46:19.380145 #1]  INFO -- : [192.168.1.110] method=GET path=/ format=html controller=Balance::HomeController action=index status=302 allocations=546 duration=16.56 view=0.00 db=0.00 location=http://192.168.1.232:3000/house_power/now
dashboard-1  | I, [2024-12-07T19:46:19.608114 #1]  INFO -- : [192.168.1.110] method=GET path=/house_power/now format=html controller=Balance::HomeController action=index status=200 allocations=18951 duration=174.06 view=170.25 db=0.00
```

**Comment by ledermann** [comment]
Danke für den Hinweis und die Geduld, ist behoben in `custom-consumers-77`.
